// <auto-generated />
namespace Application.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class rename_user_table : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(rename_user_table));
        
        string IMigrationMetadata.Id
        {
            get { return "202302020725596_rename_user_table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
